// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MaterialIconsGenerator
{
    static class Vsix
    {
        public const string Id = "e1bf5443-bf81-49e6-bc33-004e1f1f7b02";
        public const string Name = "Material icons generator";
        public const string Description = @"This extension helps you to add material design icons to your Android, iOS or UWP project";
        public const string Language = "en-US";
        public const string Version = "2.0.0";
        public const string Author = "Nika Nikabadze";
        public const string Tags = "xamarin, android, ios, material design, icons";
    }
}
