// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSMaterialIcons
{
    static class Vsix
    {
        public const string Id = "e1bf5443-bf81-49e6-bc33-004e1f1f7b02";
        public const string Name = "Material icons generator";
        public const string Description = @"This plugin help you to set material design icons to your Android project";
        public const string Language = "en-US";
        public const string Version = "1.1.2";
        public const string Author = "Nika Nikabadze";
        public const string Tags = "xamarin, android, material design, icons    ";
    }
}
